import { expect, it } from "vitest";
import oracle from "./source-parity.json";
import { promise, counter } from "./test-fixtures";
import { analyzeExtractedOaciqDocuments } from "./parser";

// Expectations generated by the external Python source, not the TS port.
for (const [name, expected] of Object.entries(oracle.cases)) it(`1474422 Python/TypeScript parity: ${name}`,()=>{
  const pa=promise({date:"2026-09-02",financing:16,documents:0});
  pa.pages[0].text=pa.pages[0].text.replace("6.2","4.1 Prix 450000 $\n4.2\n6.2").replace("23 novembre 2026","15 mars 2027").replace("27 novembre 2026 12h00","à la signature de l'acte de vente");
  const docs=[pa];
  if(name!=="pa") {
    const cp=counter({number:"20001",notary:false,occupation:false,accepted:"2026-09-03T12:00:00-04:00",refused:name==="refused"});
    if(name==="price") cp.pages[0].text=cp.pages[0].text.replace("P2.3.2","P2.3.1 Prix 475000 $\nP2.3.2");
    if(["notary","successive","refused"].includes(name)) cp.pages[0].text=cp.pages[0].text.replace("P2.3.2","P2.3.2 5 février 2027");
    if(name==="time") cp.pages[0].text=cp.pages[0].text.replace("P2.3.3","P2.3.3 15h00");
    if(name==="cancel") cp.pages[0].text=cp.pages[0].text.replace("P2.3.4","P2.3.4 La clause 8.1 est annulée.");
    docs.push(cp);
    if(name==="successive") {
      const last=counter({target:"20001",notary:false,occupation:false,accepted:"2026-09-04T10:00:00-04:00"});
      last.pages[0].text=last.pages[0].text.replace("P2.3.3","P2.3.3 7 février 2027");docs.push(last);
    }
  }
  for(const order of [docs,[...docs].reverse()]) {
    const a=analyzeExtractedOaciqDocuments(order);
    expect({price:a.finalPrice,notary:a.transactionDates.deed_of_sale_date,occupancy:a.transactionDates.occupancy_date,time:a.deadlines.find(d=>d.type==="occupancy")?.dueTime || null,inspection:a.transactionDates.inspection_deadline,financing:a.transactionDates.financing_deadline}).toEqual(expected);
  }
});
